# A subnet designed for use by a single GKE cluster.
# Capacity:
# ~1k nodes (/22)
# ~65k pods (/16)
# ~65k services (/16)
# Recommended pods per node: 64
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: platform-project-id-example-us-east4 # {"$kpt-set":"subnet-name"}
  # Landing Zone networks & subnets are managed in the networking namespace
  namespace: networking # {"$kpt-set":"networking-namespace"}
  annotations:
    cnrm.cloud.google.com/project-id: network-project-id # {"$kpt-set":"network-project-id"}
spec:
  description: platform-project-id-example-us-east4 # {"$kpt-set":"subnet-name"}
  region: us-east4 # {"$kpt-set":"location"}
  networkRef:
    external: projects/network-project-id/global/networks/default # {"$kpt-set":"network-selflink"}
  ipCidrRange: 10.3.4.0/22 # {"$kpt-set":"node-ip-range"}
  secondaryIpRange:
  - ipCidrRange: 172.17.0.0/16 # {"$kpt-set":"pod-ip-range"}
    rangeName: pods
  - ipCidrRange: 172.18.0.0/16 # {"$kpt-set":"service-ip-range"}
    rangeName: services
  privateIpGoogleAccess: true
  # Uncomment to enable VPC Flow Logs
  # https://cloud.google.com/vpc/docs/using-flow-logs
  # logConfig:
  #   aggregationInterval: INTERVAL_10_MIN
  #   flowSampling: 0.5
  #   metadata: INCLUDE_ALL_METADATA
